- name: Remove default install packages that I do not use
  package: name={{ item }} state=absent
  with_items:
    - rhythmbox

- name: Install packages that do not need configuration file changes
  package: name={{ item }} state=latest
  with_items:
    - alacarte
    - cockpit
    - gnome-music
    - gnome-tweaks
    - gparted
    - gstreamer
    - gstreamer-plugins-base
    - python-unversioned-command
    - python3-psutil
    - python3-mutagen
    - sl
    - tilix
    - youtube-dl
#    - https://atom-installer.github.com/v1.32.2/atom.x86_64.rpm
