- name: Install nano
  package: name=nano

- name: Uncomment line from /etc/nanorc to include all syntax highlighting.
  replace:
    path: /etc/nanorc
    regexp: '^#\s*include "/usr/share/nano/\*.nanorc".*$'
    replace: 'include "/usr/share/nano/*.nanorc"'
    backup: yes

- name: Add customizations to .nanorc file
  blockinfile:
    path: /home/mpedder/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      set tabsize 2 
      set tabstospaces
    backup: yes
