- name: Install nano
  package: 
    name: 
      - nano
    state: latest

- name: Uncomment line from /etc/nanorc to include all syntax highlighting.
  replace:
    path: /etc/nanorc
    regexp: '^#\s*include "/usr/share/nano/\*.nanorc".*$'
    replace: 'include "/usr/share/nano/*.nanorc"'
    backup: yes

- name: Create backup directory for nano
  file:
    path: /home/mpedder/nano-backups
    state: directory
    owner: mpedder
    group: mpedder
    mode: 0700

- name: Add customizations to .nanorc file
  blockinfile:
    path: /home/mpedder/.nanorc
    create: yes
    owner: mpedder
    group: mpedder
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      set autoindent
      set backup
      set constantshow
      set backupdir "/home/mpedder/nano-backups"
      set tabsize 2 
      set tabstospaces
    backup: yes
